name: C/C++ CI

on: [push]

jobs:
  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: print env
      run: |
        echo github.event.action: ${{ github.event.action }}
        echo github.event_name: ${{ github.event_name }}
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release
    - name: test
      run: cd build && ctest
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: .\build\release\phone_res_tool.exe
        name: phone_res_tool.exe

    - name: Upload release asset
      if: github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'created')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .\build\release\phone_res_tool.exe
        asset_name: phone_res_tool.zip
        asset_content_type: application/zip